services:
  - type: web
    name: lungguard
    env: python
    region: oregon
    plan: free
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run LungGuard_Home.py
